name: lebedew_app
description: "Lebedew App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  provider: ^6.0.5
  get_it: ^7.2.0
  path_provider: ^2.1.1
  uuid: ^3.0.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  intl: ^0.19.0
  http: ^1.1.2
  logging: ^1.2.0
  image: ^4.1.7
  shared_preferences: ^2.0.17
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true 